unit TestTest1Unit;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, AdaptersUnit, System.Generics.Collections, Test1Unit, TestsUnit,
  AccessAdapterUnit;

type
  // Test methods for class Test1

  TestTest1 = class(TTestCase)
  strict private
    Fest1: Test1;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestsetTest;
    procedure TestgetQuest;
    procedure TestgetAnswer;
    procedure TestgetCorrect;
  end;

implementation

procedure TestTest1.SetUp;
begin
  Fest1 := Test1.Create;
end;

procedure TestTest1.TearDown;
begin
  Fest1.Free;
  Fest1 := nil;
end;

procedure TestTest1.TestsetTest;
var
  caption: string;
  ReturnValue1: TList<string>;
begin
  caption:='Test2';
  Fest1.setTest(caption);
  CheckEquals(caption, 'Test2');
  ReturnValue1:=Fest1.getQuest;
  CheckEquals(ReturnValue1.Items[0], 'Дайте определение материальной точки.');
end;

procedure TestTest1.TestgetQuest;
var
  ReturnValue: TList<string>;
begin
  ReturnValue := Fest1.getQuest;
  Fest1.setTest('Test2');
  ReturnValue:=Fest1.getQuest;
  CheckEquals(ReturnValue.Items[2], 'Что такое декартова система координат?');
  CheckNotEquals(ReturnValue.Items[0], '');
  CheckEquals(ReturnValue.Count, 23);

end;

procedure TestTest1.TestgetAnswer;
var
  ReturnValue: TList<string>;
begin
  ReturnValue := Fest1.getAnswer;
  Fest1.setTest('Test2');
  ReturnValue:=Fest1.getAnswer;
  CheckEquals(ReturnValue.Items[1],
    'это координата, которую имеет МТ в данный момент времени');
  CheckNotEquals(ReturnValue.Items[3], 'ууууу');
  CheckNotEquals(ReturnValue.Items[1], 'nnnnnnnn');
  CheckEquals(ReturnValue.Count, 10);
  CheckNotEquals(ReturnValue.Count, 3);

end;

procedure TestTest1.TestgetCorrect;
var
  ReturnValue: TDictionary<integer, integer>;
begin
  ReturnValue := Fest1.getCorrect;
  CheckEquals(ReturnValue.Items[1], 1);
  CheckEquals(ReturnValue.Items[2], 2);
  CheckNotEquals(ReturnValue.Items[2], 1);
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTest1.Suite);
end.

